modLoader="${mod_loader}"
loaderVersion = "${mod_loader_version_range}"
license = "${license}"
issueTrackerURL="${issue_tracker_url}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "${logo_file}"
displayURL ="${display_url}"
displayTest = "${display_test}"
authors = "${mod_author}"
description = '''${description}'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${mod_loader_version_range}"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
